### ISSUE TITLE
Enforce site color based on location in structure

### ISSUE THREAD

**Issue by enenra** [Space-Engineers-Modding/modding-reference#10]
One thing that I think helps a lot to situate the user is that different parts of SEMREF are colored in set colors. Every page below /reference/ should always be blue, every page below /tutorials/ green, every page below /tools/ orange and every page below /mods/ purple. If we link to pages in other sections *within* a section, the color should be that of the target section.

This is already mostly the case but has to be assigned manually like so:
```
layout: doc
title: Setup Guide
excerpt: A tutorial on the installation of SEUT and its supplementary files.
date: 2020-02-28
icon:
  type: fa
  name: fa-map-marker
color: green  <-------------------------------------
```
It would be great if this color-value was automatically forced based on where in the structure the page is located, as described above. Would save times and prevent mistakes.

Additionally, and this may be too annoying to implement, it would be ideal if any "text hyperlink", so a link within the text of the page itself using `[bla](link)`, would be colored in the target pages color. So, if I link to a section of the documentation of SEUT from the SEUT page in /tools/, all links are orange by default (due to that being the tools color). But by linking to documentation within /references/, which is blue, the link on the SEUT tool page would appear in that blue.
